### ISSUE TITLE
Blocks keyboard input with 8.2

### ISSUE THREAD

**Issue by PaulVlahosCS** [kevinclement/simplearmory-addon#1]
Addon seems to cause your keyboard to not be able to input into wow for patch 8.2

**Comment by booitsme3109** [comment]
Can confirm this, same for me as well.

**Comment by tdufala** [comment]
This may have been a Blizzard bug that has since been resolved, because I'm no longer experiencing this issue.

**Comment by seirl** [comment]
I have never encountered this issue so I'll trust your judgment here, closing!
