### ISSUE TITLE
Toy exporter doesn't enable all the filters when listing the toys

### ISSUE THREAD

**Issue by SQLLord** [kevinclement/simplearmory-addon#4]
I just tried to use the addon to see what toys i have and what i dont have.  It is missing a bunch of shadowlands ones in particular but i believe BFA is missing a bunch as well.  This is one in particular that the addon is not reporting right.  https://www.wowhead.com/item=182729/hearty-dragon-plume#comments  I use this toy all the time and it says i dont have it.

**Comment by seirl** [comment]
Fixed in f9008806c5a1353c7c9060c72801ac10a83d9e13, available as v0.10 on curseforge.
